addPlayer("kit", {
    "France - Romania": "3 - 0",
    "Albania - Switzerland": "1 - 0",
    "Wales - Slovakia": "1 - 2",
    "England - Russia": "2 - 1",
    "Turkey - Croatia": "1 - 1",
    "Poland - Northern Ireland": "2 - 0",
    "Germany - Ukraine": "2 - 0",
    "Spain - Czech Republic": "3 - 0",
    "Ireland - Sweden": "0 - 1",
    "Belgium - Italy": "1 - 1",
    "Austria - Hungary": "3 - 1",
    "Portugal - Iceland": "3 - 1",
    "Russia - Slovakia": "1 - 2",
    "Romania - Switzerland": "1 - 1",
    "France - Albania": "3 - 0",
    "England - Wales": "2 - 1",
    "Ukraine - Northern Ireland": "2 - 0",
    "Germany - Poland": "2 - 2",
    "Italy - Sweden": "1 - 0",
    "Czech Republic - Croatia": "1 - 1",
    "Spain - Turkey": "3 - 0",
    "Belgium - Ireland": "1 - 1",
    "Iceland - Hungary": "3 - 1",
    "Portugal - Austria": "2 - 2",
    "Romania - Albania": "1 - 1",
    "Switzerland - France": "0 - 3",
    "Slovakia - England": "1 - 2",
    "Russia - Wales": "2 - 1",
    "Northern Ireland - Germany": "0 - 4",
    "Ukraine - Poland": "0 - 2",
    "Croatia - Spain": "0 - 3",
    "Czech Republic - Turkey": "0 - 2",
    "Hungary - Portugal": "0 - 3",
    "Iceland - Austria": "1 - 2",
    "Sweden - Belgium": "1 - 2",
    "Italy - Ireland": "2 - 0"
});
