var games = [
    "France - Romania",
    "Albania - Switzerland",
    "Wales - Slovakia",
    "England - Russia",
    "Turkey - Croatia",
    "Poland - Northern Ireland",
    "Germany - Ukraine",
    "Spain - Czech Republic",
    "Ireland - Sweden",
    "Belgium - Italy",
    "Austria - Hungary",
    "Portugal - Iceland",
    "Russia - Slovakia",
    "Romania - Switzerland",
    "France - Albania",
    "England - Wales",
    "Ukraine - Northern Ireland",
    "Germany - Poland",
    "Italy - Sweden",
    "Czech Republic - Croatia",
    "Spain - Turkey",
    "Belgium - Ireland",
    "Iceland - Hungary",
    "Portugal - Austria",
    "Romania - Albania",
    "Switzerland - France",
    "Slovakia - England",
    "Russia - Wales",
    "Northern Ireland - Germany",
    "Ukraine - Poland",
    "Croatia - Spain",
    "Czech Republic - Turkey",
    "Hungary - Portugal",
    "Iceland - Austria",
    "Sweden - Belgium",
    "Italy - Ireland"
];

var scores = [
    "3 - 0",
    "1 - 1",
    "1 - 3",
    "0 - 1",
    "3 - 2",
    "1 - 1",
    "4 - 1",
    "2 - 0",
    "0 - 2",
    "3 - 1",
    "2 - 1",
    "4 - 1",
    "2 - 1",
    "2 - 1",
    "5 - 1",
    "2 - 0",
    "1 - 2",
    "2 - 2",
    "2 - 1",
    "1 - 3",
    "0 - 2",
    "3 - 1",
    "2 - 3",
    "3 - 2",
    "1 - 0",
    "1 - 2",
    "1 - 0",
    "2 - 1",
    "0 - 3",
    "2 - 0",
    "2 - 2",
    "2 - 3",
    "2 - 2",
    "2 - 4",
    "1 - 2",
    "1 - 0"
];

var guesses = {};
for (var i in games)
    guesses[games[i]] = scores[i];

addPlayer("msjolund", guesses);
