addPlayer("mthurlin", {
    "France - Romania": "1 - 0",
    "Albania - Switzerland": "0 - 1",
    "Wales - Slovakia": "0 - 0",
    "England - Russia": "1 - 0",
    "Turkey - Croatia": "1 - 1",
    "Poland - Northern Ireland": "1 - 0",
    "Germany - Ukraine": "1 - 0",
    "Spain - Czech Republic": "1 - 0",
    "Ireland - Sweden": "0 - 2",
    "Belgium - Italy": "0 - 0",
    "Austria - Hungary": "1 - 0",
    "Portugal - Iceland": "1 - 0",
    "Russia - Slovakia": "1 - 0",
    "Romania - Switzerland": "0 - 1",
    "France - Albania": "1 - 0",
    "England - Wales": "1 - 0",
    "Ukraine - Northern Ireland": "1 - 0",
    "Germany - Poland": "1 - 0",
    "Italy - Sweden": "1 - 0",
    "Czech Republic - Croatia": "0 - 1",
    "Spain - Turkey": "1 - 0",
    "Belgium - Ireland": "1 - 0",
    "Iceland - Hungary": "0 - 0",
    "Portugal - Austria": "1 - 0",
    "Romania - Albania": "1 - 0",
    "Switzerland - France": "0 - 1",
    "Slovakia - England": "0 - 1",
    "Russia - Wales": "1 - 0",
    "Northern Ireland - Germany": "0 - 2",
    "Ukraine - Poland": "1 - 1",
    "Croatia - Spain": "1 - 1",
    "Czech Republic - Turkey": "1 - 1",
    "Hungary - Portugal": "0 - 1",
    "Iceland - Austria": "0 - 1",
    "Sweden - Belgium": "1 - 1",
    "Italy - Ireland": "2 - 0"
});
